Bugfix/download svg
togostanza/togostanza-utils pull request #13
Opened 2022-12-27 02:10 UTC by YukikoNoda

ユーザーページからのダウンロードがエラーが出る件について、12/26(月)に話合ったように`getComputedStyle`からstyleを取得する方法に変更しました。
ご確認をお願いしします。

2022-12-28 04:43 UTC, neznayer requested changes
コメントしました、ご確認をお願いいたします。 🙇

2022-12-28 04:43 UTC, neznayer commented on index.js
> +    return { [name]: getComputedStyle(root.host.stanzaInstance.element).getPropertyValue(name) };
`getComputedStyle(root.host.stanzaInstance.element)` を `.map(...)` のなかで毎回呼び出す意味がないかと思います。
`.map` の前に、変数を作って、
```javascript
const elementComputedStyle = getComputedStyle(root.host.stanzaInstance.element);
const styleWithCustom = hostStyle.match(/(--)[^\,\:\)]+/g).map( name => {
    return { [name]: elementComputedStyle.getPropertyValue(name) };
  }
)

2023-01-05 01:30 UTC, YukikoNoda commented
@neznayer 変数`elementComputedStyle`を作成し、`getComputedStyle`を毎回呼び出さないようにしました。
ご確認をお願いします。

2023-01-05 04:53 UTC, neznayer approved these changes
ありがとうございます！ 🙇‍♂️

2023-01-12 00:24 UTC, penqe approved these changes
ありがとうございます

2023-01-12 00:24 UTC, merged