Feature/css spinner
togostanza/togostanza-utils pull request #3
Opened 2022-06-15 09:13 UTC by YukikoNoda

Loading Spinnerを追加しました。
ご確認をお願いします。
<img width="822" alt="LoadingSpinner_0615" src="https://user-images.githubusercontent.com/47429234/173790571-1c0f3efd-0f47-4c58-afd2-6f24d616e619.png">

2022-06-17 01:55 UTC, YukikoNoda reviewed
exportを追加し、async,awaitを削除しました。

2022-06-17 05:39 UTC, YukikoNoda reviewed
spinnerのサイズと色を変更しました。

2022-06-21 05:10 UTC, penqe requested changes
コメントしました。

2022-06-21 05:10 UTC, penqe commented on load-data.js
>  import * as d3 from "d3";
single quote と double quote が散見される
どちらかに揃えたい

2022-06-21 05:10 UTC, penqe commented on load-data.js
>      .attr("id", "metastanza-loading-icon-div")
セミコロンをつけないコーディングスタイルもありますが、このようなケースを見るとあった方が良いですかねー。

2022-06-21 05:10 UTC, penqe commented on load-data.js
> +    .append('div')
インデントの付け方は揃えた方が良さそう

2022-06-21 05:10 UTC, penqe commented on load-data.js
> +  // const root = element.getRootNode();
プルリク出す時には、不要なコードは削除した方が良いでしょう

2022-06-21 05:10 UTC, penqe commented on load-data.js
> +    console.log(style)
プルリク時にはログも消してください。

2022-06-21 05:10 UTC, penqe commented on load-data.js
> +    console.log(style)
こういう書き方もできますかね。最近可能になった書き方です。
```
if (style) {
  style.remove();
}
```
↓
```
style?.remove();
```

2022-06-21 05:10 UTC, penqe commented on load-data.js
>  //   return array1;
けす

2022-06-21 05:10 UTC, penqe commented on load-data.js
> +    --LOADING_SPINNER_BACKGROUND: ${color};
大文字にしているのには理由はありますか？

2022-06-21 05:48 UTC, YukikoNoda reviewed
- シングルクォートをダブルクォートに全て統一し直しました。
- インデントの統一を行いました。
- 文末のセミコロン付与の統一をしました。

~~if文の書き方と、~~ 変数の大文字の書き方に関しては後ほどアントンさんに確認出来次第変更を行います。

2022-06-21 06:24 UTC, YukikoNoda reviewed
残っていたconsole.logの削除と、if文を` ?.`を使用して書き直しました。

2022-06-21 07:09 UTC, penqe commented
> 変数の大文字に関しては後ほどアントンさんに確認を行います。

大文字のままでも不具合はないのだけど、一般的には定数に使います。
CSS variables は普通定数のように使うので、ある意味正しいのかもしれない。
でもあまり見たことないので、深い理由がない限り小文字の方が良いでしょう。

2022-06-21 07:29 UTC, YukikoNoda reviewed
CSS variablesの変数を大文字から小文字へ変更しました。

2022-06-21 09:12 UTC, penqe approved these changes
ありがとうございます

2022-06-21 09:12 UTC, merged